import type { Metadata } from 'next'

import { Provider } from '@/components/ui/provider'
import { NextAuthProvider } from '@/provider/next-auth'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <NextAuthProvider>
      <html lang="ja" suppressHydrationWarning>
        <body suppressHydrationWarning>
          <Provider>{children}</Provider>
        </body>
      </html>
    </NextAuthProvider>
  )
}
